languageBox = [
        'Apache',
        'Bash',
        'C#',
        'C++',
        'CSS',
        'CoffeeScript',
        'Diff',
        'HTML',
        'HTTP',
        'Ini',
        'JSON',
        'Java',
        'JavaScript',
        'Makefile',
        'Markdown',
        'Nginx',
        'Obj-C',
        'PHP',
        'Perl',
        'Python',
        'Ruby',
        'SQL',
        'Shell',
        ]

expirationDate = [
        'Burn After Reading',
        '10 Minutes',
        '1 Hour',
        '1 Day',
        '7 Days',
        'Forever',
        ]
